name: CI
on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: hatemstartups
  REPO: hatemstartups/sample-python-ghactions

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all commits
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uvicorn fastapi requests pylint pytest pytest-cov selenium playwright

      - name: Running pytest
        run: |
          pytest -v  --cov --cov-report=xml --cov-report=html

      - name: Analysing the code with pylint
        continue-on-error: true
        run: |
          pylint app --disable=missing-docstring
          pylint tests --disable=missing-docstring

      - name: SonarCloud Scan
<<<<<<< HEAD
        uses: SonarSource/sonarcloud-github-action@v1.3
=======
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=hatemstartups-1
            -Dsonar.projectKey=sample-python-ghactions
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=app/
            -Dsonar.test.exclusions=tests/**
            -Dsonar.tests=tests/
            -Dsonar.verbose=true
>>>>>>> 05a99c4b799e5a6004559802bb217efb93fbab29
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Semantic versioning
        id: versioning
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          format: "v${major}.${minor}.${patch}-prerelease${increment}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REPO }}:latest,${{ env.REPO }}:${{ steps.versioning.outputs.version }}

      - name: Create Release
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: ${{ steps.versioning.outputs.version }}
          prerelease: true
